### ISSUE TITLE
can't unittest components using the router hook

### ISSUE THREAD

**Issue by hbinkle** [Daimler/mo360-ftk#15] opened 2020-11-16 10:04 UTC
Hi,
I know I need to wrapp components I'd like to into the `App` component to work around an issue with the i18n hook.
But this does not work for the router hook.
I'm not able to test any component using the router hook.
A simple test like:
![image](https://user-images.githubusercontent.com/51942180/99239427-56b66280-27fb-11eb-8b2c-b433269bc9bf.png)

results in the error:

![image](https://user-images.githubusercontent.com/51942180/99239484-69309c00-27fb-11eb-9ea7-97afa647bcd5.png)

**Comment by fafa0803** [comment] 2020-11-26 09:00
Hi @hbinkle ,

someone from the team will look into this and give you feedback. I am sorry for the late response. 

Fabian Faulhaber, fabian.faulhaber@daimler.com, Daimler AG on behalf of Daimler TSS GmbH.
[Imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md).

**Comment by prode81** [comment] 2020-11-27 18:29
Hey @hbinkle,

I could recreate your issue within your project, the RouterService seems not to be bound to the container in this case. 
So far I had no luck finding a solution for this or narrowing the issue down.
We might need to get the core developers involved, which might take a while, but we will come back to you, as soon as possible.
____
Acting on behalf of Daimler TSS GmbH.

**Comment by prode81** [comment] 2021-02-05 14:33
A core-developer is assigned to take care of this issue. We keep you informed about any progress.
___
Acting on behalf of Daimler TSS GmbH.

**Comment by prode81** [comment] 2021-02-23 15:18
@hbinkle could you provide a zip with a minimal example for this issue?
My recreation of this issue is lost and I don't want to provide a wrong example from memory.
___
Acting on behalf of Daimler TSS GmbH.

**Comment by prode81** [comment] 2021-02-27 11:31
This issue can simply be reproduced, by using the Router outside of the Route itself (works with hooks or classes).

`ts
import { withInject, inject, RouterService } from '@daimler/ftk-core';
import React, { Component } from 'react';

class TestContainer extends Component<{}, {}> {
  @inject()
  public router!: RouterService;

  public render(): JSX.Element {
    return <>{this.router.getRoute().name}</>;
  }
}

export default withInject(TestContainer);
`

and then in the App.tsx simply

`ts
...
<StateProvider>
  <TestContainer />
  <Route />
</StateProvider>
...
`

It's a pitty, as there could be some reasons to render stuff outsider the route that would require access to the router, like a static menu which should not rerender on route-change.
___
Acting on behalf of Daimler TSS GmbH.

**Comment by hbinkle** [comment] 2021-03-03 07:30
@prode81, thanks.
wrapping all my components using the useRouter hook with the Route component is a good workaround.
But I suggest change the hook/di to simply return undefined instead of raising an exception, like many other react hook implementations do.

**Comment by prode81** [comment] 2021-03-05 12:30
We discussed this issue and came to the conclusion, that surpressing the error would not be a good design.
Using the route component as a wrapper to mock the router-component seems to be a valid approach.
___
Acting on behalf of Daimler TSS GmbH.

**Comment by hbinkle** [comment] 2021-03-08 07:23
ok, I can live with this, but it's not a common behavior. Usually hooks depending on a context simply return undefined instead of throwing an exception.
However in this case I suggest to change the error message pointing how to solve the issue like appending:
`"Did you miss to wrap you component with the 'Route' component?"`

**Closed** 2021-03-08 07:26 UTC
Labels: wontfix

**Comment by prode81** [comment] 2021-03-08 09:56
@hbinkle I will bring this up, in our next discussion, seems to be a good approach.
___
Acting on behalf of Daimler TSS GmbH.
